### PR TITLE
Add a poly-only mGB mode

### PR DESCRIPTION
**Pull request by dhorlick**
Adds a Polyphonic-only mGB mode for users of musical keyboards [that can't change MIDI channel](https://www.youtube.com/watch?v=c2-QXARQN3o&t=8m08s) (which is most inexpensive keyboards currently in production, I believe.)

Also, minor comment edits.

Thanks for the awesome hardware!

### CODE REVIEW

**Comment by catskull** [comment]
Thanks for the PR! Wondering though, wouldn't you just change the channel that's currently set for polyphonic mode so you don't have to add another mode? I know the max editor is a little funky to get working, but it does support that configuration. I'd even be open to just changing the default poly channel in the units I ship.

**Comment by dhorlick** [comment]
I think that changing the default is a good idea! I mistakenly anticipated opposition to that approach, which is why I pursued a new mode here, instead.

I'll go ahead and close the pull request.

Regarding the max editor: In addition to having to lug around and power a computer, I gather that I'd need Max 8, and that I'd be obliged to license it after 30 days. If so, it would be cheaper just to buy a better keyboard!

**Comment by catskull** [comment]
Well you'd only have to actually change the setting once, not every time.

However I think the real solution is to re-write the editor using web midi so any browser could work.

**Comment by cyberic99** [comment]
In the end, I suppose the max editor just sends sysexes or special midi messages, right?

**Comment by dhorlick** [comment]
> Well you'd only have to actually change the setting once, not every time.

I missed that all settings saved to EEPROM. Neat!

> However I think the real solution is to re-write the editor using web midi so any browser could work.

Any browser that isn't Firefox or Safari, I guess. That'd be cool as long as the editor actually tells you the reason it's not working is that you aren't in Chrome, etc.

> In the end, I suppose the max editor just sends sysexes or special midi messages, right?

I expect so.

**Pull request closed without merging**
